language: node_js
node_js:
- '16'
services:
- docker
notifications:
  email: false
  slack:
    rooms:
      secure: OnFJ4UcsPVYQbzfSz/hm6jjshC9yISGyQl5RTa6oRneaXWXTfbs3e8WiurHlbEv867TV/rrj8klrIJsAjljtTTKvlGI1Lq2BzFoXGynWXjaQnQXpy1RCk1fAk1VrssrOr7D/GSDO+PdfsXRCeUO/ZDWEJKe06F2BXqQdCxmvTaMVJFqPxRefs+vLLmgdoAIR050nByREXveFAavo0WjDhzIa3gvhR9CWe7zyka8e7qSIh+SZj5QbeJ3SSN3+BHp08rFBVM/P5nwZToAT6Tp9InevyQLz/wYHo5W+VRXRm8OiDH+XU2CEkSAeburDaIEynHUNjbw3LUmxely4SHt7CzLcThhz3vzvIBUlWap8KLFkJHA0wRACByjQSdQZB/Oxr9PP/+Dtv4pIG+ICroFwq4bgqCI+3NZMlQdT9dOdMXO0hjZuo4bHVwMYYfVFrH6T4Uy3OoRcTwlzE8ZDMRy4C+9bdDvkqW8UCMraNDB5k65oB6Jva9gimlBbhHLYoe0SoL2IiLRSj/EubXpI89/04S+84JOz6nmre+WFUU0gM7VYh86yPtSyZoMGoj/9XYlLEL9WSEeMX/ZoucTHd/vXk4qniBwauFqQj8tvh8HidgTFMlgdGmt6AtOyE0Wb4PPvVsYNWahpXyvzEP4MBnJO2zXmRB/RAyJ+qgesCYZca9Q=
    on_success: always
    on_failure: always
env:
- JOB=osm-boundaries
- JOB=admin-express
- JOB=bdpr
script:
- |
  REPO_SLUG="$TRAVIS_REPO_SLUG"
  IMAGE_NAME=${REPO_SLUG,,} # to lowercase
  if [[ -z "$TRAVIS_TAG" ]]; then
    IMAGE_TAG=latest
    KRAWLER_TAG=latest
  else
    IMAGE_TAG=$(node -p -e "require('./package.json').version")
    KRAWLER_TAG=$(node -p -e "require('./package.json').peerDependencies['@kalisio/krawler']")
  fi
  docker build --build-arg KRAWLER_TAG=$KRAWLER_TAG -f dockerfile."$JOB" -t $IMAGE_NAME:"$JOB"-$IMAGE_TAG .
before_deploy:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push $IMAGE_NAME:"$JOB"-$IMAGE_TAG
  on:
    all_branches: true
